# Generated by Django 3.1.7 on 2021-04-27 19:23

from django.db import migrations
import embed_video.fields


class Migration(migrations.Migration):

    dependencies = [
        ('youTubeVideos', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='video',
            name='title',
        ),
        migrations.AddField(
            model_name='video',
            name='video',
            field=embed_video.fields.EmbedVideoField(default=0),
        ),
    ]
