# Generated by Django 3.1.7 on 2021-04-27 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('youTubeVideos', '0002_auto_20210427_1323'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='title',
            field=models.CharField(default=0, max_length=50),
        ),
    ]
