# Generated by Django 3.1.7 on 2021-04-27 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('youTubeVideos', '0003_video_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
