# Generated by Django 3.1.7 on 2021-04-28 01:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('youTubeVideos', '0004_auto_20210427_1406'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
